# Generated by Django 2.1.1 on 2019-06-04 06:39

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('food', models.IntegerField()),
                ('mandatory', models.IntegerField()),
                ('essentials', models.IntegerField()),
                ('travel', models.IntegerField()),
                ('shopping', models.IntegerField()),
                ('booze', models.IntegerField()),
                ('entertainment', models.IntegerField()),
                ('people', models.IntegerField()),
                ('others', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('Comments', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MemberUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
