# Generated by Django 2.1.1 on 2019-06-04 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exp_trac_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expenditures',
            new_name='Expenditure',
        ),
    ]
