# Generated by Django 2.1.1 on 2019-06-13 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Exp_trac_app', '0003_auto_20190611_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='member_user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
