# Generated by Django 2.1.1 on 2019-06-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp_trac_app', '0004_expenditure_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberuser',
            name='is_logged_in_for_first_time',
            field=models.BooleanField(default=True),
        ),
    ]
