# Generated by Django 2.1.1 on 2019-06-14 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Exp_trac_app', '0005_memberuser_is_logged_in_for_first_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('is_logged_in_for_first_time', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='memberuser',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='expenditure',
            name='member_user',
        ),
        migrations.DeleteModel(
            name='MemberUser',
        ),
        migrations.AddField(
            model_name='expenditure',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile', to='Exp_trac_app.Profile'),
            preserve_default=False,
        ),
    ]
