# Generated by Django 2.1.1 on 2019-06-15 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Exp_trac_app', '0006_auto_20190614_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_logged_in_for_first_time',
            new_name='first_login',
        ),
        migrations.RemoveField(
            model_name='expenditure',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
        migrations.AddField(
            model_name='expenditure',
            name='mem_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Expense', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
