# Generated by Django 2.1.1 on 2019-06-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp_trac_app', '0007_auto_20190616_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='per_day_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
